from datetime import datetime
from database.session_repo import get_session_messages

def export_session_as_markdown(session_id, user_stage="", target_domain="", messages=None):
    """Compiles a session into a structured Markdown report."""
    if messages is None:
        messages = get_session_messages(session_id)
    if not messages:
        return "# CareNex AI Career Guidance Report\n\nNo messages in this session."

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    md = "# 🎓 CareNex AI Career Guidance Report\n\n"
    md += f"**Date:** {now_str}  \n"
    if user_stage:
        md += f"**Profile:** {user_stage}  \n"
    if target_domain:
        md += f"**Domain:** {target_domain}  \n"
    md += f"**Session ID:** `{session_id}`  \n"
    md += "\n---\n\n"

    for i, msg in enumerate(messages, 1):
        role_title = "🧑‍💻 User" if msg["role"] == "user" else "⚡ CareNex"
        md += f"### {role_title}\n\n"
        md += f"{msg['content']}\n\n"
        md += "---\n\n"

    return md

def export_session_as_text(session_id, user_stage="", target_domain="", messages=None):
    """Compiles a session into a clean Plaintext (.txt) document."""
    if messages is None:
        messages = get_session_messages(session_id)
    if not messages:
        return "CARENEX CAREER GUIDANCE REPORT\nNo messages in this session."

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    sep = "=" * 70
    sub_sep = "-" * 70

    lines = [
        sep,
        "CARENEX - AI CAREER GUIDANCE CONSULTATION REPORT",
        sep,
        f"Date:           {now_str}",
        f"Career Stage:   {user_stage or 'General'}",
        f"Target Domain:  {target_domain or 'All Domains'}",
        f"Session ID:     {session_id}",
        sep,
        ""
    ]

    for i, msg in enumerate(messages, 1):
        sender = "USER" if msg["role"] == "user" else "CARENEX"
        lines.append(f"[{sender}]:")
        lines.append(msg["content"].strip())
        lines.append("")
        lines.append(sub_sep)
        lines.append("")

    return "\n".join(lines)

def export_session_as_pdf(session_id, user_stage="", target_domain="", messages=None):
    """Compiles a session into a formatted PDF Document (.pdf) bytes."""
    from fpdf import FPDF

    if messages is None:
        messages = get_session_messages(session_id)
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")

    class CareerPDF(FPDF):
        def header(self):
            self.set_font('Helvetica', 'B', 11)
            self.set_text_color(0, 180, 160)
            self.cell(0, 8, 'CareNex AI - Career Guidance Report', new_x='LMARGIN', new_y='NEXT')
            self.set_draw_color(220, 225, 230)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(140, 150, 160)
            self.cell(0, 10, f'Page {self.page_no()}/{{nb}}  |  Generated by CareNex AI Career Platform', align='C')

    def sanitize(text):
        if not text:
            return ""
        rep = {
            '🤖': '[CareNex]', '🧑‍💻': '[User]', '⚡': '[CareNex]', '🗺️': '[Roadmap]',
            '💼': '[Career]', '🎤': '[Interview]', '•': '-', '—': '--', '–': '-',
            '’': "'", '“': '"', '”': '"', '‘': "'", '👉': '->', '✅': '[OK]',
            '⚠️': '[Warning]', '💡': '[Tip]', '🔥': '[Trending]', '🚀': '[Launch]',
            '🎯': '[Goal]', '🌟': '[Star]', '⭐': '[Star]', '📌': '[Action]',
            '🔍': '[Search]', '📊': '[Data]', '🛠️': '[Tools]', '🛠': '[Tools]',
            '📚': '[Study]', '🎓': '[Edu]', '📈': '[Growth]', '✨': '[Key]'
        }
        for k, v in rep.items():
            text = text.replace(k, v)
        return text.encode('latin-1', 'replace').decode('latin-1')

    pdf = CareerPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title & Metadata Banner
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'CareNex Career Guidance Consultation', new_x='LMARGIN', new_y='NEXT')
    
    pdf.set_font('Helvetica', size=9)
    pdf.set_text_color(90, 105, 125)
    meta_info = f"Date: {now_str}  |  Stage: {user_stage or 'General'}  |  Domain: {target_domain or 'All Domains'}"
    pdf.cell(0, 6, sanitize(meta_info), new_x='LMARGIN', new_y='NEXT')
    pdf.ln(5)

    if not messages:
        pdf.set_font('Helvetica', 'I', 11)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 8, 'No messages recorded in this consultation session.', new_x='LMARGIN', new_y='NEXT')
    else:
        for msg in messages:
            is_user = (msg["role"] == "user")
            
            # Role Header
            pdf.set_x(pdf.l_margin)
            pdf.set_font('Helvetica', 'B', 10)
            if is_user:
                pdf.set_text_color(0, 102, 204)
                pdf.cell(0, 7, 'User Query:', new_x='LMARGIN', new_y='NEXT')
            else:
                pdf.set_text_color(0, 150, 120)
                pdf.cell(0, 7, 'CareNex Mentorship:', new_x='LMARGIN', new_y='NEXT')

            # Message Content
            pdf.set_font('Helvetica', size=9.5)
            pdf.set_text_color(30, 41, 59)
            clean_body = sanitize(msg["content"].strip())
            
            # Render using epw width safely
            pdf.set_x(pdf.l_margin)
            try:
                pdf.multi_cell(w=pdf.epw, h=5.5, text=clean_body, markdown=True)
            except Exception:
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(w=pdf.epw, h=5.5, text=clean_body, markdown=False)
            pdf.ln(4)

            # Divider line
            pdf.set_draw_color(230, 235, 240)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(4)

    return bytes(pdf.output())
